[build]
  command = "npm run build"
  publish = "dist"
  base = "client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_API_URL = "Your API URL (e.g. https://your-app.onrender.com/api)"