version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./server
    container_name: spotify-backend
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/spotify
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  mongodb_data: